#!/bin/sh

if [ -f .env ]; then
    set -a
    . ./.env
    set +a
fi

if ! ./gradlew build -x test; then
    echo "Gradle build failed. Commit aborted." >&2
    exit 1
fi

echo "Gradle build success!" >&2
exit 0
